# The URL the site will be built for
base_url = "https://particle.vercel.app"

theme = "particle-zola"

title = "BlackSheepRobotics"
description = "A blog about lorem ipsum dolor sit amet"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

# The default language; used in feeds.
default_language = "en"

[extra]
# User settings
username = "BlackSheepRobotics"
user_description = "Developer/Engineer by Day, Father/Roboticist/Rocketeering by Night"
user_title = "Software Developer"
email = "mailto:blacksheeprobotics<at>gmail.com"
#twitter_username = "lorem_ipsum"
github_username =  "https://github.com/blacksheeprobotics"
#gplus_username =  "lorem_ipsum"

# Google-analytics
google_analytics.id = ""
